とりあえず(半)自動でwandboxサービスを用意できる状態

diff --git a/build-all-packages b/build-all-packages
--- a/build-all-packages
+++ b/build-all-packages
@@ -1,15 +1,141 @@
 #!/bin/sh
 
-set -e
+export TZ=Etc/UTC
+export LANG=C
+unset LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
+nodownload=false
+skiphead=false
+all=false
+clean=""
+keep=false
+opt="$1"
+pass=""
+roomba=false
+headdate=$(date +%Y%m%d)
+
+while [ -n "$opt" ]; do
+  true
+  case "$opt" in
+  -h|--h|--he|--hel|--help)
+    echo "usage: $0 [--skip-head] [--all] [--clean] [--keep-going] [--head-date=\$(date +%Y%m%d)] [--nodownload] [--roomba] [--pass=pkg,pkg,...]"
+    exit
+    ;;
+  -n|--n|--no|--nod|--nodo|--nodow|--nodown|--nodownl|--nodownlo|--nodownloa|--nodownload)
+    nodownload=true
+    shift
+    ;;
+  -s|--s|--sk|--ski|--skip|--skip-|--skip-h|--skip-he|--skip-hea|--skip-head|--skip-heads)
+    skiphead=true
+    shift
+    ;;
+  -a|--a|--al|--all)
+    all=true
+    shift
+    ;;
+  -c|--c|--cl|--cle|--clea|--clean)
+    clean=-c
+    shift
+    ;;
+  -k|--k|--ke|--kee|--keep|--keep-|--keep-g|--keep-go|--keep-goi|--keep-goin|--keep-going)
+    keep=true
+    shift
+    ;;
+  -p|--p|--pa|--pas|--pass|--p=*|--pa=*|--pas=*|--pass=*)
+    if echo $1 | grep -q =; then
+      pass="$pass $(echo "$1" | cut -d= -f2 | sed 's/,/ /g')"
+    else
+      pass="$pass $(echo "$2" | sed 's/,/ /g')"
+      shift
+    fi
+    shift
+    ;;
+  -r|--r|--ro|--roo|--room|--roomb|--roomba)
+    roomba=true
+    shift
+    ;;
+  -h|--h|--he|--hea|--head|--head-|--head-d|--head-da|--head-dat|--head-date|--h=*|--he=*|--hea=*|--head=*|--head-=*|--head-d=*|--head-da=*|--head-dat=*|--head-date=*)
+    if echo $1 | grep -q =; then
+      headdate="$(echo "$1" | cut -d= -f2)"
+    else
+      headdate="$2"
+      shift
+    fi
+    shift
+  esac
+  opt="$1"
+done
+
+faillist=""
+post_fail() {
+  if $keep; then
+    faillist="$faillist $1"
+  else
+    echo "failed to build package $2: $1"
+  fi
+  false
+}
+test_need_to_build() {
+  # $0 pkgname pkgver pkgrel
+  local oldver="$(dpkg-query -W -f '${Version}' "$1" 2> /dev/null)"
+  if ( echo $1 | grep -q ".-head\|.-maint" ) && date -d "$2" + > /dev/null 2> /dev/null; then
+    if $skiphead; then
+      return 1
+    fi
+    if dpkg --compare-versions "$oldver" ge "${headdate}-$3"; then
+      return 1
+    fi
+  elif dpkg --compare-versions "$oldver" ge "$2-$3"; then
+    return 1
+  fi
+  return 0
+}
+$keep || set -e
 cd "$(dirname "$0")"
-./fetch-sources
-./gen-boost-spec
-for pkg in $(cat series); do
+if $roomba; then
+  rm -rf $(rpm --eval='%{_builddir} %{_buildrootdir} %{_rpmdir} %{_specdir} %{_srcrpmdir}')
+  mkdir -p $(rpm --eval='%{_builddir} %{_buildrootdir} %{_rpmdir} %{_specdir} %{_srcrpmdir}')
+fi
+$nodownload || ./fetch-sources
+echo -n "generating specs"
+for genspec in genspec/*; do
+  echo -n "."
+  $genspec
+done
+echo "done"
+for pkg in $(cat series/*); do
+  echo -n "preparing for $pkg..."
+  if [ -z "$pkg" ] || (echo " $pass " | grep -q " $pkg "); then
+    echo " skip."
+    continue
+  fi
+  echo
+  if [ ! -f "specs/$pkg.spec" ]; then
+    post_fail $pkg "spec does not exist"
+    $keep && continue || break
+  fi
+  if ! rpmspec --srpm -q specs/$pkg.spec --qf "%{NAME}%{VERSION}%{RELEASE}" > /dev/null 2> /dev/null; then
+    post_fail $pkg "(malformed SPEC file)"
+    $keep && continue || break
+  fi
   pkgname="$(rpmspec --srpm -q specs/$pkg.spec --qf "%{NAME}")"
   pkgver="$(rpmspec --srpm -q specs/$pkg.spec --qf "%{VERSION}")"
   pkgrel="$(rpmspec --srpm -q specs/$pkg.spec --qf "%{RELEASE}")"
-  if dpkg --compare-versions "$(dpkg-query -W -f '${Version}' "${pkgname}" 2> /dev/null)" lt "${pkgver}-${pkgrel}"; then
-    ./build-deb-from-spec specs/$pkg.spec
-    sudo dpkg -i "${pkgname}_${pkgver}-${pkgrel}_$(dpkg-architecture -c 'echo $DEB_HOST_ARCH').deb"
+  if $all || test_need_to_build $pkgname $pkgver $pkgrel; then
+    mkdir -p buildlog
+    if ./build-deb-from-spec specs/$pkg.spec $clean 2>&1 | tee buildlog/$pkg.log; then
+      if ! sudo dpkg -i "deb/${pkgname}_${pkgver}-${pkgrel}_$(dpkg-architecture -c 'echo $DEB_HOST_ARCH').deb"; then
+        post_fail $pkg "(alien failed)"
+        $keep || break
+      fi
+    else
+      post_fail $pkg
+      $keep || break
+    fi
   fi
 done
+
+if [ -n "$faillist" ]; then
+  echo "failed to build package(s):"
+  echo "$faillist"
+  false
+fi
diff --git a/fetch-sources b/fetch-sources
--- a/fetch-sources
+++ b/fetch-sources
@@ -1,8 +1,12 @@
 #!/bin/bash
 
 declare -A SHA1
+declare -A SHA256
 declare -A MD5
+declare -A GPG
 declare -A NOVERIFY
+declare -A SITE
+declare -A SVN
 
 srcdir=$(realpath "$(dirname "$0")")
 . sources.list
@@ -11,15 +15,32 @@ cksum() {
   echo "$2  $3" | ${1}sum --check
 }
 fetch() {
-  if echo "$1" | grep -q '://'; then
-    wget "$1"
+  local site="${SITE[$1]:-$1}"
+  if echo "$site" | grep -q '://'; then
+    curl -L "$site" -o "$(basename "$1")"
+  elif [[ -n "${SVN[$1]}" ]]; then
+    if ! [[ -f "$1" ]]; then
+      local r="${SVN[$1]}"
+      local d="$(mktemp -d)"
+      ( cd "$d" && svn export -q "$r" "$(echo $(basename "$1") | sed 's/\.tar\(\.gz\|\.bz2\|\.Z\|\.xz\|\.lzma\)\?$//')" && tar caf "$1" * ) && \
+      mv "$d/$1" . && \
+      mv -rf "$d"
+    fi
   else
     cp "$srcdir/sources/$1" .
   fi
 }
+gpg_wrap() {
+  gpg --no-options --homedir "$srcdir/pubkeys" --no-permission-warning "$@"
+}
 
 (
+  trap "exit 1" SIGTERM
+  trap "exit 1" SIGQUIT
   success=true
+  for f in "$srcdir"/pubkeys/*.asc; do
+    gpg_wrap --import $f
+  done
   cd
   mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
   cd rpmbuild/SOURCES
@@ -36,6 +57,24 @@ fetch() {
       continue
     fi
     if ! cksum sha1 "$s" "$f"; then
+      echo "checksum unmatch: $k" >&2
+      success=false
+      continue
+    fi
+  done
+  for k in ${!SHA256[@]}; do
+    f="$(basename "$k")"
+    s="${SHA256[$k]}"
+    if [ -f "$f" ] && cksum sha256 "$s" "$f"; then
+      continue
+    fi
+    rm -f "$f"
+    if ! fetch "$k"; then
+      echo "failed to download: $k" >&2
+      success=false
+      continue
+    fi
+    if ! cksum sha256 "$s" "$f"; then
       echo "checksum unmatch: $k" >&2
       success=false
       continue
@@ -59,11 +98,27 @@ fetch() {
       continue
     fi
   done
-  for k in ${!NOVERIFY[@]}; do
+  for k in ${!GPG[@]}; do
     f="$(basename "$k")"
-    if [ -f "$f" ]; then
+    s="${GPG[$k]:-.sig}"
+    if [ -f "$f" -a -s "$f$s" ] && gpg_wrap --verify "$f$s" 2> /dev/null; then
+      echo "$f: OK"
       continue
     fi
+    rm -f "$f"
+    if ! fetch "$k" || ! fetch "$k$s" ; then
+      echo "failed to download: $k" >&2
+      success=false
+      continue
+    fi
+    if ! gpg_wrap --verify "$f$s" ; then
+      echo "signature unmatch: $k" >&2
+      success=false
+      continue
+    fi
+  done
+  for k in ${!NOVERIFY[@]}; do
+    f="$(basename "$k")"
     if ! fetch "$k"; then
       echo "failed to download: $k" >&2
       success=false
